name: build
on:
  push:
    branches:
    - v2.0.9
  pull_request:
    branches:
    - v2.0.9
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          #- os: windows-latest
          #  platform: win32-x64
          - os: ubuntu-latest
            platform: linux-x64
          #- os: ubuntu-20.04
          #  platform: linux-arm64
          #- os: macos-latest
          #  platform: darwin-x64
          #- os: macos-latest
          #  platform: darwin-arm64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake lua compile/download_deps.lua
    - run: luamake -mode release -platform ${{ matrix.platform }}
    #- run: npm install -g vsce ovsx
    #- run: npx vsce publish --target ${{ matrix.platform }} -p ${{ secrets.VSCE_KEY }}
    #  working-directory: publish
    #  continue-on-error: true
    #- run: npx ovsx publish --target ${{ matrix.platform }} -p ${{ secrets.OVSX_KEY }}
    #  working-directory: publish
    #  continue-on-error: true
