name: build
on:
  push:
    branches:
    - linux-static-linkage
  pull_request:
    branches:
    - linux-static-linkage
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          #- os: windows-latest
          #  platform: win32-x64
          - os: ubuntu-latest
            platform: linux-x64
          - os: ubuntu-24.04-arm
            platform: linux-arm64
          #- os: macos-latest
          #  platform: darwin-x64
          #- os: macos-latest
          #  platform: darwin-arm64
    steps:
    - uses: actions/checkout@v4
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - if: matrix.platform == 'linux-x64' || matrix.platform == 'linux-arm64'
      run: |
        sudo apt update && sudo apt install -y libiberty-dev
    - run: luamake lua compile/download_deps.lua
    - run: luamake -mode release -platform ${{ matrix.platform }}
    #- run: npm install -g @vscode/vsce ovsx
    #- run: npx vsce publish --target ${{ matrix.platform }} -p ${{ secrets.VSCE_KEY }}
    #  working-directory: publish
    #  continue-on-error: true
    #- run: npx ovsx publish --target ${{ matrix.platform }} -p ${{ secrets.OVSX_KEY }}
    #  working-directory: publish
    #  continue-on-error: true
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact-${{matrix.platform}}
        path: publish/
        retention-days: 7 # Keep the artifact for 7 days
